# Generated by Django 2.1.7 on 2019-03-06 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_date', models.DateField(auto_now=True, verbose_name='Дата загрузки')),
                ('abc3', models.FileField(upload_to='download/', verbose_name='Файл ABC-3xx.csv')),
                ('abc4', models.FileField(upload_to='download/', verbose_name='Файл ABC-4xx.csv')),
                ('abc8', models.FileField(upload_to='download/', verbose_name='Файл ABC-8xx.csv')),
                ('abc9', models.FileField(upload_to='download/', verbose_name='Файл ABC-9xx.csv')),
            ],
            options={
                'verbose_name': 'Загруженные данные',
                'verbose_name_plural': 'Загруженные данные',
            },
        ),
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Оператор',
                'verbose_name_plural': 'Операторы',
            },
        ),
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abc', models.PositiveIntegerField(verbose_name='Код (первые три цифры)')),
                ('start_number', models.PositiveIntegerField(verbose_name='От')),
                ('end_number', models.PositiveIntegerField(verbose_name='До')),
            ],
            options={
                'verbose_name': 'Диапазон телефонных номеров',
                'verbose_name_plural': 'Диапазоны телефонных номеров',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent', models.CharField(blank=True, max_length=255, null=True, verbose_name='Вышестоящий субъект')),
                ('name', models.CharField(max_length=255, verbose_name='Регион')),
            ],
            options={
                'verbose_name': 'Регион',
                'verbose_name_plural': 'Регионы',
            },
        ),
    ]
