# Generated by Django 2.1.7 on 2019-03-08 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloaddata',
            name='abc3',
            field=models.FileField(blank=True, null=True, upload_to='download/', verbose_name='Файл ABC-3xx.csv'),
        ),
        migrations.AlterField(
            model_name='downloaddata',
            name='abc4',
            field=models.FileField(blank=True, null=True, upload_to='download/', verbose_name='Файл ABC-4xx.csv'),
        ),
        migrations.AlterField(
            model_name='downloaddata',
            name='abc8',
            field=models.FileField(blank=True, null=True, upload_to='download/', verbose_name='Файл ABC-8xx.csv'),
        ),
        migrations.AlterField(
            model_name='downloaddata',
            name='abc9',
            field=models.FileField(blank=True, null=True, upload_to='download/', verbose_name='Файл ABC-9xx.csv'),
        ),
    ]
