# Generated by Django 2.1.7 on 2019-03-08 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190308_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonenumber',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Operator', verbose_name='Оператор'),
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Region', verbose_name='Регион'),
        ),
    ]
