# Generated by Django 2.1.7 on 2019-03-08 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190308_2110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='downloaddata',
            name='abc9',
        ),
        migrations.AddField(
            model_name='downloaddata',
            name='def9',
            field=models.FileField(blank=True, null=True, upload_to='download/', verbose_name='Файл DEF-9xx.csv'),
        ),
    ]
