version: '3.0'

services:
  db:
    image: postgres:11-alpine
    container_name: do_db
    volumes:
      - "./data/db:/var/lib/postgresql/data"
    env_file:
      - ./.env
    ports:
      - 5432:5432

  redis:
    image: redis:5-alpine
    container_name: do_redis
    env_file:
      - ./.env
    ports:
      - 6379:6379

  celery_worker:
    image: algol2302/defop-backend
    container_name: do_celery_worker
    volumes:
    - "./data/media:/opt/media"
    env_file:
    - ./.env
    depends_on:
    - db
    - redis
    entrypoint: bash ./run_backends.sh celery_worker

  celery_beat:
    image: algol2302/defop-backend
    container_name: do_celery_beat
    volumes:
    - "./data/media:/opt/media"
    env_file:
    - ./.env
    depends_on:
    - db
    - redis
    entrypoint: bash ./run_backends.sh celery_beat

  backend:
    image: algol2302/defop-backend
    container_name: do_backend
    volumes:
      - "./data/media:/opt/media"
      - "../certs:/opt/certs:ro"
    ports:
      - 8000:8000
    env_file:
      - ./.env
    entrypoint: bash ./run_backends.sh server

  nginx:
    image: algol2302/defop-nginx
    container_name: do_nginx
    volumes:
      - "./data/media:/opt/media:ro"
      - "./nginx/conf/nginx.conf:/etc/nginx/conf.d/default.conf:ro"
    ports:
      - 1080:80
    depends_on:
      - backend
